# Generated by Django 4.0.5 on 2022-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_testimonial_product_date_added_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=60, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
