# Generated by Django 4.0.5 on 2022-06-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
